/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 Duck.gltf
*/

import React, { useRef } from 'react'
import { useGLTF, PerspectiveCamera } from '@react-three/drei'

export default function(props) {
  const { nodes, materials } = useGLTF('/model/duck/duck.gltf')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        {/* <PerspectiveCamera makeDefault={false} far={10000} near={1} fov={37.849} position={[400.113, 463.264, -431.078]} rotation={[-2.314, 0.566, 2.614]} /> */}
        <mesh geometry={nodes.LOD3spShape.geometry}  material-color={"yellow"}/>
        {/* <mesh geometry={nodes.LOD3spShape.geometry} material={materials['blinn3-fx']}  material-color={"red"}/> */}
      </group>
    </group>
  )
}

useGLTF.preload('/model/duck/duck.gltf')
