/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 scene.gltf
Author: Ikal.Ichwan (https://sketchfab.com/Ikal.Ichwan)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/t-shirt-polo-lengan-pendek-74c33d16b31346f1a46a55c3ec8e8a78
Title: T-shirt Polo Lengan Pendek
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function(props) {
  const { nodes, materials } = useGLTF('/model/ShirtScene/scene.gltf')
  return (
    <group {...props} dispose={null} scale={3}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.Back_FRONT_2239} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.Button_FRONT_2249} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.Collar_FRONT_2229} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.Front_FRONT_2234} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.PT_FABRIC_FRONT_2281} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.Upper_Left_FRONT_2219} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.Upper_Right_FRONT_2209} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.Back_FRONT_2239} />
        <mesh geometry={nodes.Object_10.geometry} material={materials.Button_FRONT_2249} />
        <mesh geometry={nodes.Object_11.geometry} material={materials.Collar_FRONT_2229} />
        <mesh geometry={nodes.Object_12.geometry} material={materials.Front_FRONT_2234} />
        <mesh geometry={nodes.Object_13.geometry} material={materials.Lower_Left_FRONT_2224} />
        <mesh geometry={nodes.Object_14.geometry} material={materials.Lower_Right_FRONT_2214} />
        <mesh geometry={nodes.Object_15.geometry} material={materials.Material115145} />
        <mesh geometry={nodes.Object_16.geometry} material={materials.Pocket_FRONT_2244} />
        <mesh geometry={nodes.Object_17.geometry} material={materials.Upper_Left_FRONT_2219} />
        <mesh geometry={nodes.Object_18.geometry} material={materials.Upper_Right_FRONT_2209} />
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
